use_frameworks!

platform :ios, '8.0'

target 'XVIEWPublicManager_Example' do
  pod 'XVIEWPublicManager', :path => '../'

  target 'XVIEWPublicManager_Tests' do
    inherit! :search_paths

    
  end
end
